### ISSUE TITLE
Invert Hold Your Horses Hotkey

### ISSUE THREAD

**Issue by daltonpearson** [skeldoor/hold-your-ground#1]
it would be nice to be able to invert the behavior of the HYH Hotkey. So instead of the hotkey disabling HYH it would instead enable HYH while the hotkey is held.

**Comment by skeldoor** [comment]
I've added this in the latest version. Just awaiting runelite admin approval now. Thanks for the suggestion.

**Comment by daltonpearson** [comment]
@skeldoor thanks that's awesome!

**Comment by skeldoor** [comment]
This is now live.
