### ISSUE TITLE
Plugin is incompatible and need to be updated by the author

### ISSUE THREAD

**Issue by frkwhiteangel** [skeldoor/hold-your-ground#3]
Plugin is incompatible and need to be updated by the author for it to function with current RuneLite.

**Comment by skeldoor** [comment]
Hi, this has been fixed in the upcoming version 1.0.2 just currently awaiting approval from the Runelite team to be put live.

You can track the progress of that here https://github.com/runelite/plugin-hub/pull/6100

**Comment by skeldoor** [comment]
This is fixed now.
